export const projects = [
  {
    id: 12,
    name: "Buyinsurance",
    description:
      "The buyinsurance web portal streamlines the process of buying life insurance policies from Sanlam. it is user-friendly, making it simple for users to obtain insurance quotes and purchase policies",
    api: true,
    languages: ["Node js, ", "ReactJS, ", "HTML5, ", "CSS3 "],
    img: "https://fbn-service-staging.s3.eu-west-1.amazonaws.com/files/0D1fzBjrzgRayn8YHVaqBbHnKFqrYjrdEHkxJ7h0.png",
    link: "http://buyinsurance.sanlam.com.ng/",
    repository: "https://github.com/efethegenius/E-Streams",
    type: "webApp",
  },
  {
    id: 11,
    name: "E-Streams",
    description:
      "See the full details & trailers of your favourite movies, latest movies and tv series. It Utilizes the TMDB api so the movies on the application are always up to date!",
    api: true,
    languages: ["Javascript Es6+, ", "ReactJS, ", "HTML5, ", "CSS3 "],
    img: "https://fbn-service-staging.s3.eu-west-1.amazonaws.com/files/dB7Ibmj9zgbd8Lwpx1UR1anpV1FNAM9v8Tri64ir.png",
    link: "https://estreams.netlify.app/",
    repository: "https://github.com/efethegenius/E-Streams",
    type: "webApp",
  },
  {
    id: 1,
    name: "Invoice App",
    description:
      "A web application that can be used to create invoices, store, manage, and delete invoices. it is a web app that is ready for use by businesses or companies!",
    api: false,
    languages: ["Javascript Es6+, ", "ReactJS, ", "HTML5, ", "CSS3 "],
    img: "https://fbn-service-staging.s3.eu-west-1.amazonaws.com/files/5RiaaLtEKEeOGzAcD4kQMoOhXVxL34EiG19bv1ky.png",
    link: "https://topinvoice.netlify.app/",
    repository: "https://github.com/efethegenius/invoice-app",
    type: "webApp",
  },
  {
    id: 12,
    name: "Afarmacco",
    description:
      "afarmacco enables poultry farmers to maintain their daily operational records, keep records of financial transactions,apply medications to secure your birds & lots more.",
    api: true,
    languages: ["Javascript Es6+, ", "ReactJS, ", "HTML5, ", "CSS3 "],
    img: "https://fbn-service-staging.s3.eu-west-1.amazonaws.com/files/cUsjaIe81DaKBZeXcaXGXczkYUsHOGtgsoIf6wnp.png",
    link: "https://afarmacco.netlify.app/",
    repository: "https://github.com/efethegenius/afarmacco",
    type: "webApp",
  },
  {
    id: 2,
    name: "Countries App",
    description:
      "A web application containing the details of every single country on earth and 1000+ facts of all countries on earth.",
    api: true,
    languages: ["Javascript Es6+, ", "ReactJS, ", "HTML5, ", "CSS3 "],
    img: "https://fbn-service-staging.s3.eu-west-1.amazonaws.com/files/Ju0w65oVQaJdas4CxntIvEMPoPmlAJ0SWRRGTTkz.png",
    link: "https://e-countries.netlify.app/",
    repository: "https://github.com/efethegenius/Countries-app",
    type: "webApp",
  },
  {
    id: 3,
    name: "Developer Jobs",
    description:
      "A webapp for developer job searchers. contains multiple job listings!",
    api: false,
    languages: ["Javascript Es6+, ", "ReactJS, ", "HTML5, ", "CSS3 "],
    img: "https://fbn-service-staging.s3.eu-west-1.amazonaws.com/files/cNqtEYwh2YsZRUGxmC9hjUAkpKIeZolCWiMPutxT.png",
    link: "https://mydevjobs.netlify.app/",
    repository: "https://github.com/efethegenius/devjobs",
    type: "webApp",
  },
  {
    id: 4,
    name: "Planet Facts",
    description:
      "A fun styled web app that displays the planets in our solar system and facts/stats about the planet!",
    api: false,
    languages: ["Javascript Es6+, ", "ReactJS, ", "HTML5, ", "CSS3 "],
    img: "https://fbn-service-staging.s3.eu-west-1.amazonaws.com/files/xXlTK6YWyWiwQ0Ekv4wBWHpDrBXjxGKoSoBFgJxq.png",
    link: "https://my-planet-facts.netlify.app/",
    repository: "https://github.com/efethegenius/planets-facts",
    type: "webApp",
  },
  // {
  //   id: 5,
  //   name: "The Sunnyside",
  //   description:
  //     "A simple but classy landing page for a graphics designer/photographer brand",
  //   api: false,
  //   languages: ["Javascript Es6+, ", "ReactJS, ", "HTML5, ", "CSS3 "],
  //   img: "https://v5.airtableusercontent.com/v1/16/16/1683842400000/zIRCvLTfNOvFHOJD4bhJ0g/EawD2v5DvfTgnZcXscHRyq2ZA61_GSzzVcsZqQDki35Byp3HQsuDlzFo0FDQ_77QjD9vgDm3hKhlbBVZ9HJ3ow/pw1WYuv2bnS-8_2LRKsRGWv7wi9xP5vW90-EjGnKSTs",
  //   link: "https://thesunnyside.netlify.app/",
  //   repository: "https://github.com/efethegenius/sunnyside",
  //   type: "website",
  // },
  {
    id: 6,
    name: "Space Tourism",
    description:
      "A multipage Space Tourism website. It is a concept website that gives you the opportunity to visit other planets in space!",
    api: false,
    languages: ["Javascript Es6+, ", "HTML5, ", "CSS3 "],
    img: "https://fbn-service-staging.s3.eu-west-1.amazonaws.com/files/roSXZigWCuN6lrIqp1Z94yiTNTLnRaO793oPBBlr.png",
    link: "https://spacetours.netlify.app/",
    repository: "https://github.com/efethegenius/space-tourism",
    type: "website",
  },
  {
    id: 7,
    name: "Crowdfunding App",
    description:
      "This web application is a concept crowdfunding app that gives you the ability to donate money to a cause.",
    api: false,
    languages: ["Javascript Es6+, ", "ReactJS, ", "HTML5, ", "CSS3 "],
    img: "https://fbn-service-staging.s3.eu-west-1.amazonaws.com/files/TWrQmEhqjLHhkp3Gu5ZuGKJAW4U4lVMbrUJ1ylVW.png",
    link: "https://mycrowdfunding.netlify.app/",
    repository: "https://github.com/efethegenius/crowdfunding",
    type: "webApp",
  },
  // {
  //   id: 8,
  //   name: "WindBnb",
  //   description:
  //     "I love the airbnb UI, it is so modern and clean. in this project, i built a similar UI to airbnb - Windbnb",
  //   api: true,
  //   languages: ["Javascript Es6+, ", "ReactJS, ", "HTML5, ", "CSS3 "],
  //   img: "https://dl.airtable.com/.attachmentThumbnails/7432e0812b18427d923d4f39a8694ac4/787ee2c7",
  //   link: "https://mywindbnb.netlify.app/",
  //   repository: "https://github.com/efethegenius/windbnb",
  //   type: "webApp",
  // },
  // {
  //   id: 9,
  //   name: "Loopstudios VR",
  //   description:
  //     "This is just a simple static one page website for a VR company/business",
  //   api: false,
  //   languages: ["Javascript Es6+, ", "ReactJS, ", "HTML5, ", "CSS3 "],
  //   img: "https://dl.airtable.com/.attachmentThumbnails/2cb9018c872acf1d3c572c0454f8caaa/8a6c5c0f",
  //   link: "https://my-loopstudios.netlify.app/",
  //   repository: "https://github.com/efethegenius/loopstudios",
  //   type: "website",
  // },
  {
    id: 10,
    name: "My Portfolio",
    description: "That's right, this one...",
    api: false,
    languages: ["Javascript Es6+, ", "ReactJS, ", "HTML5, ", "CSS3 "],
    img: "https://fbn-service-staging.s3.eu-west-1.amazonaws.com/files/FVvFOjAb2BkMlWENXKW7SmBdREIa2bTb8aKDqIHK.png",
    link: "https://efesamuel.netlify.app/",
    repository: "https://github.com/efethegenius/my-portfolio",
    type: "website",
  },
];
