export const projects = [
  {
    id: 11,
    name: "E-Streams",
    description:
      "See the full details & trailers of your favourite movies, latest movies and tv series. It Utilizes the TMDB api so the movies on the application are always up to date!",
    api: true,
    languages: ["Javascript Es6+, ", "ReactJS, ", "HTML5, ", "CSS3 "],
    img: "https://v5.airtableusercontent.com/v1/16/16/1683842400000/0VwYukLJSg2ra8Vh5And4A/nsJYT1ViDRMm8eEdcP_DbrFWEdWMUAziDehI3xm9U_LNZbWg2xsJotVEBYXn1gUDpue2tlN8wHeMV9wZYMQtIw/b1XY6Ko1FtIV8wZN1BSBUrCvUojm_f3A5eeo8V_jul4",
    link: "https://estreams.netlify.app/",
    repository: "https://github.com/efethegenius/E-Streams",
    type: "webApp",
  },
  {
    id: 1,
    name: "Invoice App",
    description:
      "A web application that can be used to create invoices, store, manage, and delete invoices. it is a web app that is ready for use by businesses or companies!",
    api: false,
    languages: ["Javascript Es6+, ", "ReactJS, ", "HTML5, ", "CSS3 "],
    img: "https://v5.airtableusercontent.com/v1/16/16/1683842400000/wo8gw3X68LrsTXMMSx1Bxw/mTOrTr_oNmvrnMK-ClPf6JjPTsxwkYT56ZGiQxd0QoPOnCrVjbC7tA3T8qekk17UniF-KBR5LqF3IgNH2hX3tw/UW0UNNColAeIcrhNcFhuyyUx_hp110wCJCJHuRZ4eng",
    link: "https://topinvoice.netlify.app/",
    repository: "https://github.com/efethegenius/invoice-app",
    type: "webApp",
  },
  {
    id: 12,
    name: "Afarmacco",
    description:
      "afarmacco enables poultry farmers to maintain their daily operational records, keep records of financial transactions,apply medications to secure your birds & lots more.",
    api: true,
    languages: ["Javascript Es6+, ", "ReactJS, ", "HTML5, ", "CSS3 "],
    img: "https://v5.airtableusercontent.com/v1/16/16/1683842400000/PQyUUgY5vfGVCGmn_ic1Hg/nI_mDXXqOWUEMDyZDf1oe91MZ5wT5LUDSlRSO-Kgllnw3wK1tjz6XrtsqvfK4R5Cz_5OlBJ7SkViG2On9DYUJQ/FpRMWZTB9QKzMXZVtwsFRqaMXYjbA2ZGRgh6NKVeNXg",
    link: "https://afarmacco.netlify.app/",
    repository: "https://github.com/efethegenius/afarmacco",
    type: "webApp",
  },
  {
    id: 2,
    name: "Countries App",
    description:
      "A web application containing the details of every single country on earth and 1000+ facts of all countries on earth.",
    api: true,
    languages: ["Javascript Es6+, ", "ReactJS, ", "HTML5, ", "CSS3 "],
    img: "https://v5.airtableusercontent.com/v1/16/16/1683842400000/ywAWRtT9PSCqzt7bhpzHzQ/YLpUP_ofj6qv04HWZsa6QqNiRxXrr7kepbqHJO4Y4TIhruDz7pZA0U30Qp4EowkOXu_DpfPRNQGbXcpKXJjOPw/shTJgdHz3VLF3aHBEkOeyJdOxElukDUbgS7Q6hJm5G0",
    link: "https://e-countries.netlify.app/",
    repository: "https://github.com/efethegenius/Countries-app",
    type: "webApp",
  },
  {
    id: 3,
    name: "Developer Jobs",
    description:
      "A webapp for developer job searchers. contains multiple job listings!",
    api: false,
    languages: ["Javascript Es6+, ", "ReactJS, ", "HTML5, ", "CSS3 "],
    img: "https://v5.airtableusercontent.com/v1/16/16/1683842400000/dI3kaQrFG63E2mC87a3K2Q/Q9SV5WUfxEKCW2PAEBFdjs3l-LeD3SXVmlbjLyIwqIWHJy4lkSYnYJkHfVglKmj_p5Wgz4Vp_unmbeVkH0b55Q/QZ3Ii0f199YDF1m-8XjMp_zlcw7CFTATEOBhg58YuyI",
    link: "https://mydevjobs.netlify.app/",
    repository: "https://github.com/efethegenius/devjobs",
    type: "webApp",
  },
  {
    id: 4,
    name: "Planet Facts",
    description:
      "A fun styled web app that displays the planets in our solar system and facts/stats about the planet!",
    api: false,
    languages: ["Javascript Es6+, ", "ReactJS, ", "HTML5, ", "CSS3 "],
    img: "https://v5.airtableusercontent.com/v1/16/16/1683842400000/_K8earpL2mfP4cQOUZjqqA/dQ1XMUD0SfguuKYskEw4Idfs1dzBiHpgO7XKG9V5vVopcn5FMpcZlO_8gJ7094Inq4PjXydesX4c5AEUbMjvTQ/uq9i6XISP768pXfFYqywIwqrTZ2HVAVqfUFw10kieks",
    link: "https://my-planet-facts.netlify.app/",
    repository: "https://github.com/efethegenius/planets-facts",
    type: "webApp",
  },
  {
    id: 5,
    name: "The Sunnyside",
    description:
      "A simple but classy landing page for a graphics designer/photographer brand",
    api: false,
    languages: ["Javascript Es6+, ", "ReactJS, ", "HTML5, ", "CSS3 "],
    img: "https://v5.airtableusercontent.com/v1/16/16/1683842400000/zIRCvLTfNOvFHOJD4bhJ0g/EawD2v5DvfTgnZcXscHRyq2ZA61_GSzzVcsZqQDki35Byp3HQsuDlzFo0FDQ_77QjD9vgDm3hKhlbBVZ9HJ3ow/pw1WYuv2bnS-8_2LRKsRGWv7wi9xP5vW90-EjGnKSTs",
    link: "https://thesunnyside.netlify.app/",
    repository: "https://github.com/efethegenius/sunnyside",
    type: "website",
  },
  {
    id: 6,
    name: "Space Tourism",
    description:
      "A multipage Space Tourism website. It is a concept website that gives you the opportunity to visit other planets in space!",
    api: false,
    languages: ["Javascript Es6+, ", "HTML5, ", "CSS3 "],
    img: "https://v5.airtableusercontent.com/v1/16/16/1683842400000/_xX_6ACOa8AZgLW4DWiRpA/yG3Oa4REE-wrvRcccY98ZT62dBEcDUQ_eAZ6mi1GkTywJYrceVjVW7WvSE2HSFVJMK4uWLNqm3bItSd8tixQXg/5TskUfK6Too6poR4SujdHghssJUI4xUe55IGD23Ve_M",
    link: "https://spacetours.netlify.app/",
    repository: "https://github.com/efethegenius/space-tourism",
    type: "website",
  },
  {
    id: 7,
    name: "Crowdfunding App",
    description:
      "This web application is a concept crowdfunding app that gives you the ability to donate money to a cause.",
    api: false,
    languages: ["Javascript Es6+, ", "ReactJS, ", "HTML5, ", "CSS3 "],
    img: "https://v5.airtableusercontent.com/v1/16/16/1683842400000/s9yJjXjOYytsjyfsuVDaQA/SZCOBXi6gLDS8y9F0d1MMGGUFUdVpZMckPvcLn7unZXBk1aozoNOnfVTDf8jSy7H5vKCFNy24jRBlOrNau5nXw/k8NIQrGhCQD-LdeUK1-1MVm1i2wzYEpGgrkI3IONE5k",
    link: "https://mycrowdfunding.netlify.app/",
    repository: "https://github.com/efethegenius/crowdfunding",
    type: "webApp",
  },
  // {
  //   id: 8,
  //   name: "WindBnb",
  //   description:
  //     "I love the airbnb UI, it is so modern and clean. in this project, i built a similar UI to airbnb - Windbnb",
  //   api: true,
  //   languages: ["Javascript Es6+, ", "ReactJS, ", "HTML5, ", "CSS3 "],
  //   img: "https://dl.airtable.com/.attachmentThumbnails/7432e0812b18427d923d4f39a8694ac4/787ee2c7",
  //   link: "https://mywindbnb.netlify.app/",
  //   repository: "https://github.com/efethegenius/windbnb",
  //   type: "webApp",
  // },
  // {
  //   id: 9,
  //   name: "Loopstudios VR",
  //   description:
  //     "This is just a simple static one page website for a VR company/business",
  //   api: false,
  //   languages: ["Javascript Es6+, ", "ReactJS, ", "HTML5, ", "CSS3 "],
  //   img: "https://dl.airtable.com/.attachmentThumbnails/2cb9018c872acf1d3c572c0454f8caaa/8a6c5c0f",
  //   link: "https://my-loopstudios.netlify.app/",
  //   repository: "https://github.com/efethegenius/loopstudios",
  //   type: "website",
  // },
  {
    id: 10,
    name: "My Portfolio",
    description: "That's right, this one...",
    api: false,
    languages: ["Javascript Es6+, ", "ReactJS, ", "HTML5, ", "CSS3 "],
    img: "https://v5.airtableusercontent.com/v1/16/16/1683842400000/NrjjJMIrarjESAKa8tBpdg/YQIlw9ZiI5L_3klVRq4yKVdVq3i6BeKqavXuJxrs-wTZ8Oei1ekEKyeYdjdIRyFbki_xYwEy6C11DBYleMzYlw/waMZzxeoEXTt-4OhWPrOwaz05GA8ese8Xc7UOnfix4k",
    link: "https://efesamuel.netlify.app/",
    repository: "https://github.com/efethegenius/my-portfolio",
    type: "website",
  },
];
